//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsageReportingDownloads.UsageReporting {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationInfo", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class AuthenticationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode {
            get {
                return this.AuthCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthCodeField, value) != true)) {
                    this.AuthCodeField = value;
                    this.RaisePropertyChanged("AuthCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey {
            get {
                return this.UserKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.UserKeyField, value) != true)) {
                    this.UserKeyField = value;
                    this.RaisePropertyChanged("UserKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsageGranularity", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum UsageGranularity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hourly = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Daily = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weekly = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SummaryUsageResponseItem", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class SummaryUsageResponseItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinutesViewedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UniqueUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ViewsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MinutesViewed {
            get {
                return this.MinutesViewedField;
            }
            set {
                if ((this.MinutesViewedField.Equals(value) != true)) {
                    this.MinutesViewedField = value;
                    this.RaisePropertyChanged("MinutesViewed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UniqueUsers {
            get {
                return this.UniqueUsersField;
            }
            set {
                if ((this.UniqueUsersField.Equals(value) != true)) {
                    this.UniqueUsersField = value;
                    this.RaisePropertyChanged("UniqueUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Views {
            get {
                return this.ViewsField;
            }
            set {
                if ((this.ViewsField.Equals(value) != true)) {
                    this.ViewsField = value;
                    this.RaisePropertyChanged("Views");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pagination", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class Pagination : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxNumberResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNumberResults {
            get {
                return this.MaxNumberResultsField;
            }
            set {
                if ((this.MaxNumberResultsField.Equals(value) != true)) {
                    this.MaxNumberResultsField = value;
                    this.RaisePropertyChanged("MaxNumberResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetailedUsageResponse", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class DetailedUsageResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UsageReportingDownloads.UsageReporting.DetailedUsageResponseItem[] PagedResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNumberResponsesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReportingDownloads.UsageReporting.DetailedUsageResponseItem[] PagedResponses {
            get {
                return this.PagedResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.PagedResponsesField, value) != true)) {
                    this.PagedResponsesField = value;
                    this.RaisePropertyChanged("PagedResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNumberResponses {
            get {
                return this.TotalNumberResponsesField;
            }
            set {
                if ((this.TotalNumberResponsesField.Equals(value) != true)) {
                    this.TotalNumberResponsesField = value;
                    this.RaisePropertyChanged("TotalNumberResponses");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetailedUsageResponseItem", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponseItem))]
    public partial class DetailedUsageResponseItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SecondsViewedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double StartPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SecondsViewed {
            get {
                return this.SecondsViewedField;
            }
            set {
                if ((this.SecondsViewedField.Equals(value) != true)) {
                    this.SecondsViewedField = value;
                    this.RaisePropertyChanged("SecondsViewed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double StartPosition {
            get {
                return this.StartPositionField;
            }
            set {
                if ((this.StartPositionField.Equals(value) != true)) {
                    this.StartPositionField = value;
                    this.RaisePropertyChanged("StartPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtendedDetailedUsageResponseItem", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class ExtendedDetailedUsageResponseItem : UsageReportingDownloads.UsageReporting.DetailedUsageResponseItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PlaybackSpeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponseItem.StartReasons StartReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponseItem.StopReasons StopReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PlaybackSpeed {
            get {
                return this.PlaybackSpeedField;
            }
            set {
                if ((this.PlaybackSpeedField.Equals(value) != true)) {
                    this.PlaybackSpeedField = value;
                    this.RaisePropertyChanged("PlaybackSpeed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponseItem.StartReasons StartReason {
            get {
                return this.StartReasonField;
            }
            set {
                if ((this.StartReasonField.Equals(value) != true)) {
                    this.StartReasonField = value;
                    this.RaisePropertyChanged("StartReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponseItem.StopReasons StopReason {
            get {
                return this.StopReasonField;
            }
            set {
                if ((this.StopReasonField.Equals(value) != true)) {
                    this.StopReasonField = value;
                    this.RaisePropertyChanged("StopReason");
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ExtendedDetailedUsageResponseItem.StartReasons", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
        public enum StartReasons : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Start = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Seek = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Resume = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NewSpeed = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Unknown = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Unexpected = 5,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ExtendedDetailedUsageResponseItem.StopReasons", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
        public enum StopReasons : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            End = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Seek = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Pause = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SpeedChange = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PlayerClose = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Unknown = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Unexpected = 6,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtendedDetailedUsageResponse", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class ExtendedDetailedUsageResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponseItem[] PagedResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNumberResponsesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponseItem[] PagedResponses {
            get {
                return this.PagedResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.PagedResponsesField, value) != true)) {
                    this.PagedResponsesField = value;
                    this.RaisePropertyChanged("PagedResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNumberResponses {
            get {
                return this.TotalNumberResponsesField;
            }
            set {
                if ((this.TotalNumberResponsesField.Equals(value) != true)) {
                    this.TotalNumberResponsesField = value;
                    this.RaisePropertyChanged("TotalNumberResponses");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatsReportType", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum StatsReportType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FolderUsage = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionUsage = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserViewingUsage = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCreationUsage = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastLoginTime = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionsViewsByUsers = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionsViewsByViewingType = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionsCreatedOrEdited = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemoteRecorderUsage = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemViews = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatsReportStatus", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class StatsReportStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReportIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReportTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UsageReportingDownloads.UsageReporting.StatsReportType ReportTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReportId {
            get {
                return this.ReportIdField;
            }
            set {
                if ((this.ReportIdField.Equals(value) != true)) {
                    this.ReportIdField = value;
                    this.RaisePropertyChanged("ReportId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReportTime {
            get {
                return this.ReportTimeField;
            }
            set {
                if ((this.ReportTimeField.Equals(value) != true)) {
                    this.ReportTimeField = value;
                    this.RaisePropertyChanged("ReportTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReportingDownloads.UsageReporting.StatsReportType ReportType {
            get {
                return this.ReportTypeField;
            }
            set {
                if ((this.ReportTypeField.Equals(value) != true)) {
                    this.ReportTypeField = value;
                    this.RaisePropertyChanged("ReportType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringReportCadence", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum RecurringReportCadence : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Daily = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weekly = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monthly = 30,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringStatsReportDefinition", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class RecurringStatsReportDefinition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UsageReportingDownloads.UsageReporting.RecurringReportCadence CadenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DefinitionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OffsetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UsageReportingDownloads.UsageReporting.StatsReportType ReportTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UsageReportingDownloads.UsageReporting.StatsReportStatus[] ReportsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReportingDownloads.UsageReporting.RecurringReportCadence Cadence {
            get {
                return this.CadenceField;
            }
            set {
                if ((this.CadenceField.Equals(value) != true)) {
                    this.CadenceField = value;
                    this.RaisePropertyChanged("Cadence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DefinitionId {
            get {
                return this.DefinitionIdField;
            }
            set {
                if ((this.DefinitionIdField.Equals(value) != true)) {
                    this.DefinitionIdField = value;
                    this.RaisePropertyChanged("DefinitionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEnabled {
            get {
                return this.IsEnabledField;
            }
            set {
                if ((this.IsEnabledField.Equals(value) != true)) {
                    this.IsEnabledField = value;
                    this.RaisePropertyChanged("IsEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Offset {
            get {
                return this.OffsetField;
            }
            set {
                if ((this.OffsetField.Equals(value) != true)) {
                    this.OffsetField = value;
                    this.RaisePropertyChanged("Offset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReportingDownloads.UsageReporting.StatsReportType ReportType {
            get {
                return this.ReportTypeField;
            }
            set {
                if ((this.ReportTypeField.Equals(value) != true)) {
                    this.ReportTypeField = value;
                    this.RaisePropertyChanged("ReportType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReportingDownloads.UsageReporting.StatsReportStatus[] Reports {
            get {
                return this.ReportsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportsField, value) != true)) {
                    this.ReportsField = value;
                    this.RaisePropertyChanged("Reports");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsageReporting.IUsageReporting")]
    public interface IUsageReporting {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSystemSummaryUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSystemSummaryUsageResponse")]
        UsageReportingDownloads.UsageReporting.SummaryUsageResponseItem[] GetSystemSummaryUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.DateTime beginRange, System.DateTime endRange, UsageReportingDownloads.UsageReporting.UsageGranularity granularity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSystemSummaryUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSystemSummaryUsageResponse")]
        System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.SummaryUsageResponseItem[]> GetSystemSummaryUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.DateTime beginRange, System.DateTime endRange, UsageReportingDownloads.UsageReporting.UsageGranularity granularity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetFolderSummaryUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetFolderSummaryUsageResponse")]
        UsageReportingDownloads.UsageReporting.SummaryUsageResponseItem[] GetFolderSummaryUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid folderId, System.DateTime beginRange, System.DateTime endRange, UsageReportingDownloads.UsageReporting.UsageGranularity granularity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetFolderSummaryUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetFolderSummaryUsageResponse")]
        System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.SummaryUsageResponseItem[]> GetFolderSummaryUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid folderId, System.DateTime beginRange, System.DateTime endRange, UsageReportingDownloads.UsageReporting.UsageGranularity granularity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSessionSummaryUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSessionSummaryUsageResponse")]
        UsageReportingDownloads.UsageReporting.SummaryUsageResponseItem[] GetSessionSummaryUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.DateTime beginRange, System.DateTime endRange, UsageReportingDownloads.UsageReporting.UsageGranularity granularity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSessionSummaryUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSessionSummaryUsageResponse")]
        System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.SummaryUsageResponseItem[]> GetSessionSummaryUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.DateTime beginRange, System.DateTime endRange, UsageReportingDownloads.UsageReporting.UsageGranularity granularity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSessionDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSessionDetailedUsageResponse")]
        UsageReportingDownloads.UsageReporting.DetailedUsageResponse GetSessionDetailedUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, UsageReportingDownloads.UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSessionDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSessionDetailedUsageResponse")]
        System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.DetailedUsageResponse> GetSessionDetailedUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, UsageReportingDownloads.UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSessionExtendedDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSessionExtendedDetailedUsageResponse")]
        UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponse GetSessionExtendedDetailedUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, UsageReportingDownloads.UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSessionExtendedDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSessionExtendedDetailedUsageResponse")]
        System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponse> GetSessionExtendedDetailedUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, UsageReportingDownloads.UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetUserDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetUserDetailedUsageResponse")]
        UsageReportingDownloads.UsageReporting.DetailedUsageResponse GetUserDetailedUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetUserDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetUserDetailedUsageResponse")]
        System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.DetailedUsageResponse> GetUserDetailedUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetUserExtendedDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetUserExtendedDetailedUsageResponse")]
        UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponse GetUserExtendedDetailedUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetUserExtendedDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetUserExtendedDetailedUsageResponse")]
        System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponse> GetUserExtendedDetailedUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSessionUserDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSessionUserDetailedUsageResponse")]
        UsageReportingDownloads.UsageReporting.DetailedUsageResponse GetSessionUserDetailedUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSessionUserDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSessionUserDetailedUsageResponse")]
        System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.DetailedUsageResponse> GetSessionUserDetailedUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSessionUserExtendedDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSessionUserExtendedDetailedUsageResponse")]
        UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponse GetSessionUserExtendedDetailedUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSessionUserExtendedDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSessionUserExtendedDetailedUsageResponse")]
        System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponse> GetSessionUserExtendedDetailedUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/DescribeReportTypes", ReplyAction="http://tempuri.org/IUsageReporting/DescribeReportTypesResponse")]
        UsageReportingDownloads.UsageReporting.StatsReportType[] DescribeReportTypes(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/DescribeReportTypes", ReplyAction="http://tempuri.org/IUsageReporting/DescribeReportTypesResponse")]
        System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.StatsReportType[]> DescribeReportTypesAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/DescribeReportType", ReplyAction="http://tempuri.org/IUsageReporting/DescribeReportTypeResponse")]
        string[] DescribeReportType(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, UsageReportingDownloads.UsageReporting.StatsReportType reportType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/DescribeReportType", ReplyAction="http://tempuri.org/IUsageReporting/DescribeReportTypeResponse")]
        System.Threading.Tasks.Task<string[]> DescribeReportTypeAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, UsageReportingDownloads.UsageReporting.StatsReportType reportType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetRecentReports", ReplyAction="http://tempuri.org/IUsageReporting/GetRecentReportsResponse")]
        UsageReportingDownloads.UsageReporting.StatsReportStatus[] GetRecentReports(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Nullable<UsageReportingDownloads.UsageReporting.StatsReportType> reportType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetRecentReports", ReplyAction="http://tempuri.org/IUsageReporting/GetRecentReportsResponse")]
        System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.StatsReportStatus[]> GetRecentReportsAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Nullable<UsageReportingDownloads.UsageReporting.StatsReportType> reportType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/QueueReport", ReplyAction="http://tempuri.org/IUsageReporting/QueueReportResponse")]
        System.Guid QueueReport(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, UsageReportingDownloads.UsageReporting.StatsReportType reportType, System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/QueueReport", ReplyAction="http://tempuri.org/IUsageReporting/QueueReportResponse")]
        System.Threading.Tasks.Task<System.Guid> QueueReportAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, UsageReportingDownloads.UsageReporting.StatsReportType reportType, System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetReport", ReplyAction="http://tempuri.org/IUsageReporting/GetReportResponse")]
        void GetReport(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid reportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetReport", ReplyAction="http://tempuri.org/IUsageReporting/GetReportResponse")]
        System.Threading.Tasks.Task GetReportAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid reportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/CancelReport", ReplyAction="http://tempuri.org/IUsageReporting/CancelReportResponse")]
        void CancelReport(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid reportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/CancelReport", ReplyAction="http://tempuri.org/IUsageReporting/CancelReportResponse")]
        System.Threading.Tasks.Task CancelReportAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid reportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/CreateRecurringReport", ReplyAction="http://tempuri.org/IUsageReporting/CreateRecurringReportResponse")]
        System.Guid CreateRecurringReport(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, UsageReportingDownloads.UsageReporting.RecurringReportCadence cadenceType, int cadenceOffset, UsageReportingDownloads.UsageReporting.StatsReportType reportType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/CreateRecurringReport", ReplyAction="http://tempuri.org/IUsageReporting/CreateRecurringReportResponse")]
        System.Threading.Tasks.Task<System.Guid> CreateRecurringReportAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, UsageReportingDownloads.UsageReporting.RecurringReportCadence cadenceType, int cadenceOffset, UsageReportingDownloads.UsageReporting.StatsReportType reportType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/DeleteRecurringReport", ReplyAction="http://tempuri.org/IUsageReporting/DeleteRecurringReportResponse")]
        void DeleteRecurringReport(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid reportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/DeleteRecurringReport", ReplyAction="http://tempuri.org/IUsageReporting/DeleteRecurringReportResponse")]
        System.Threading.Tasks.Task DeleteRecurringReportAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid reportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetRecurringReports", ReplyAction="http://tempuri.org/IUsageReporting/GetRecurringReportsResponse")]
        UsageReportingDownloads.UsageReporting.RecurringStatsReportDefinition[] GetRecurringReports(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Nullable<UsageReportingDownloads.UsageReporting.StatsReportType> reportType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetRecurringReports", ReplyAction="http://tempuri.org/IUsageReporting/GetRecurringReportsResponse")]
        System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.RecurringStatsReportDefinition[]> GetRecurringReportsAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Nullable<UsageReportingDownloads.UsageReporting.StatsReportType> reportType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsageReportingChannel : UsageReportingDownloads.UsageReporting.IUsageReporting, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsageReportingClient : System.ServiceModel.ClientBase<UsageReportingDownloads.UsageReporting.IUsageReporting>, UsageReportingDownloads.UsageReporting.IUsageReporting {
        
        public UsageReportingClient() {
        }
        
        public UsageReportingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsageReportingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsageReportingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsageReportingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UsageReportingDownloads.UsageReporting.SummaryUsageResponseItem[] GetSystemSummaryUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.DateTime beginRange, System.DateTime endRange, UsageReportingDownloads.UsageReporting.UsageGranularity granularity) {
            return base.Channel.GetSystemSummaryUsage(auth, beginRange, endRange, granularity);
        }
        
        public System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.SummaryUsageResponseItem[]> GetSystemSummaryUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.DateTime beginRange, System.DateTime endRange, UsageReportingDownloads.UsageReporting.UsageGranularity granularity) {
            return base.Channel.GetSystemSummaryUsageAsync(auth, beginRange, endRange, granularity);
        }
        
        public UsageReportingDownloads.UsageReporting.SummaryUsageResponseItem[] GetFolderSummaryUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid folderId, System.DateTime beginRange, System.DateTime endRange, UsageReportingDownloads.UsageReporting.UsageGranularity granularity) {
            return base.Channel.GetFolderSummaryUsage(auth, folderId, beginRange, endRange, granularity);
        }
        
        public System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.SummaryUsageResponseItem[]> GetFolderSummaryUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid folderId, System.DateTime beginRange, System.DateTime endRange, UsageReportingDownloads.UsageReporting.UsageGranularity granularity) {
            return base.Channel.GetFolderSummaryUsageAsync(auth, folderId, beginRange, endRange, granularity);
        }
        
        public UsageReportingDownloads.UsageReporting.SummaryUsageResponseItem[] GetSessionSummaryUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.DateTime beginRange, System.DateTime endRange, UsageReportingDownloads.UsageReporting.UsageGranularity granularity) {
            return base.Channel.GetSessionSummaryUsage(auth, sessionId, beginRange, endRange, granularity);
        }
        
        public System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.SummaryUsageResponseItem[]> GetSessionSummaryUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.DateTime beginRange, System.DateTime endRange, UsageReportingDownloads.UsageReporting.UsageGranularity granularity) {
            return base.Channel.GetSessionSummaryUsageAsync(auth, sessionId, beginRange, endRange, granularity);
        }
        
        public UsageReportingDownloads.UsageReporting.DetailedUsageResponse GetSessionDetailedUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, UsageReportingDownloads.UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange) {
            return base.Channel.GetSessionDetailedUsage(auth, sessionId, pagination, beginRange, endRange);
        }
        
        public System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.DetailedUsageResponse> GetSessionDetailedUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, UsageReportingDownloads.UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange) {
            return base.Channel.GetSessionDetailedUsageAsync(auth, sessionId, pagination, beginRange, endRange);
        }
        
        public UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponse GetSessionExtendedDetailedUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, UsageReportingDownloads.UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange) {
            return base.Channel.GetSessionExtendedDetailedUsage(auth, sessionId, pagination, beginRange, endRange);
        }
        
        public System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponse> GetSessionExtendedDetailedUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, UsageReportingDownloads.UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange) {
            return base.Channel.GetSessionExtendedDetailedUsageAsync(auth, sessionId, pagination, beginRange, endRange);
        }
        
        public UsageReportingDownloads.UsageReporting.DetailedUsageResponse GetUserDetailedUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination) {
            return base.Channel.GetUserDetailedUsage(auth, userId, pagination);
        }
        
        public System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.DetailedUsageResponse> GetUserDetailedUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination) {
            return base.Channel.GetUserDetailedUsageAsync(auth, userId, pagination);
        }
        
        public UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponse GetUserExtendedDetailedUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange) {
            return base.Channel.GetUserExtendedDetailedUsage(auth, userId, pagination, beginRange, endRange);
        }
        
        public System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponse> GetUserExtendedDetailedUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange) {
            return base.Channel.GetUserExtendedDetailedUsageAsync(auth, userId, pagination, beginRange, endRange);
        }
        
        public UsageReportingDownloads.UsageReporting.DetailedUsageResponse GetSessionUserDetailedUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination) {
            return base.Channel.GetSessionUserDetailedUsage(auth, sessionId, userId, pagination);
        }
        
        public System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.DetailedUsageResponse> GetSessionUserDetailedUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination) {
            return base.Channel.GetSessionUserDetailedUsageAsync(auth, sessionId, userId, pagination);
        }
        
        public UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponse GetSessionUserExtendedDetailedUsage(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination) {
            return base.Channel.GetSessionUserExtendedDetailedUsage(auth, sessionId, userId, pagination);
        }
        
        public System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.ExtendedDetailedUsageResponse> GetSessionUserExtendedDetailedUsageAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.Guid userId, UsageReportingDownloads.UsageReporting.Pagination pagination) {
            return base.Channel.GetSessionUserExtendedDetailedUsageAsync(auth, sessionId, userId, pagination);
        }
        
        public UsageReportingDownloads.UsageReporting.StatsReportType[] DescribeReportTypes(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth) {
            return base.Channel.DescribeReportTypes(auth);
        }
        
        public System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.StatsReportType[]> DescribeReportTypesAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth) {
            return base.Channel.DescribeReportTypesAsync(auth);
        }
        
        public string[] DescribeReportType(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, UsageReportingDownloads.UsageReporting.StatsReportType reportType) {
            return base.Channel.DescribeReportType(auth, reportType);
        }
        
        public System.Threading.Tasks.Task<string[]> DescribeReportTypeAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, UsageReportingDownloads.UsageReporting.StatsReportType reportType) {
            return base.Channel.DescribeReportTypeAsync(auth, reportType);
        }
        
        public UsageReportingDownloads.UsageReporting.StatsReportStatus[] GetRecentReports(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Nullable<UsageReportingDownloads.UsageReporting.StatsReportType> reportType) {
            return base.Channel.GetRecentReports(auth, reportType);
        }
        
        public System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.StatsReportStatus[]> GetRecentReportsAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Nullable<UsageReportingDownloads.UsageReporting.StatsReportType> reportType) {
            return base.Channel.GetRecentReportsAsync(auth, reportType);
        }
        
        public System.Guid QueueReport(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, UsageReportingDownloads.UsageReporting.StatsReportType reportType, System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.QueueReport(auth, reportType, startTime, endTime);
        }
        
        public System.Threading.Tasks.Task<System.Guid> QueueReportAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, UsageReportingDownloads.UsageReporting.StatsReportType reportType, System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.QueueReportAsync(auth, reportType, startTime, endTime);
        }
        
        public void GetReport(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid reportId) {
            base.Channel.GetReport(auth, reportId);
        }
        
        public System.Threading.Tasks.Task GetReportAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid reportId) {
            return base.Channel.GetReportAsync(auth, reportId);
        }
        
        public void CancelReport(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid reportId) {
            base.Channel.CancelReport(auth, reportId);
        }
        
        public System.Threading.Tasks.Task CancelReportAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid reportId) {
            return base.Channel.CancelReportAsync(auth, reportId);
        }
        
        public System.Guid CreateRecurringReport(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, UsageReportingDownloads.UsageReporting.RecurringReportCadence cadenceType, int cadenceOffset, UsageReportingDownloads.UsageReporting.StatsReportType reportType) {
            return base.Channel.CreateRecurringReport(auth, cadenceType, cadenceOffset, reportType);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateRecurringReportAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, UsageReportingDownloads.UsageReporting.RecurringReportCadence cadenceType, int cadenceOffset, UsageReportingDownloads.UsageReporting.StatsReportType reportType) {
            return base.Channel.CreateRecurringReportAsync(auth, cadenceType, cadenceOffset, reportType);
        }
        
        public void DeleteRecurringReport(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid reportId) {
            base.Channel.DeleteRecurringReport(auth, reportId);
        }
        
        public System.Threading.Tasks.Task DeleteRecurringReportAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Guid reportId) {
            return base.Channel.DeleteRecurringReportAsync(auth, reportId);
        }
        
        public UsageReportingDownloads.UsageReporting.RecurringStatsReportDefinition[] GetRecurringReports(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Nullable<UsageReportingDownloads.UsageReporting.StatsReportType> reportType) {
            return base.Channel.GetRecurringReports(auth, reportType);
        }
        
        public System.Threading.Tasks.Task<UsageReportingDownloads.UsageReporting.RecurringStatsReportDefinition[]> GetRecurringReportsAsync(UsageReportingDownloads.UsageReporting.AuthenticationInfo auth, System.Nullable<UsageReportingDownloads.UsageReporting.StatsReportType> reportType) {
            return base.Channel.GetRecurringReportsAsync(auth, reportType);
        }
    }
}
